### ISSUE TITLE
Trickster RIP? 3 years, no releases, no answers

### ISSUE THREAD

**Issue by vitalyu** [trickstercache/trickster#703]
Are you there?

**Comment by jnichols-git** [comment]
I'm closing this as duplicate since this discussion is already happening [here](https://github.com/trickstercache/trickster/issues/632). I've quoted my response today below.

To answer your immediate question, yes, we're here! Dev time has been restricted, but we're finalizing the last couple things for v2. While we work on that, community contributions are encouraged and processed fairly quickly.

> Here's where we are on the next v2 beta:
> 
> - There are some dependencies that need updating
> - The Clickhouse multi-line query is fixed, but there's an error in testing that I haven't resolved yet
> - Autodiscovery needs a couple more changes to be merged into v2
> 
> I have some time carved out this weekend to power through these items. We're getting the beta out the door as soon as we can, but please understand that we're largely volunteers that are also managing professional and personal lives. Turns out having a full-time job, like being in college, isn't super conducive to open source dev time. I wish someone had explained that to me sooner! :sweat_smile: 
> 
> Regardless, I am really sorry about the delay, and I know explanations like this don't get you an updated Trickster version. Please keep an eye on pull requests over the next couple of weeks as I wrap up these last action items--that'll be a better metric for progress than any estimate I give here.
